services:
  - type: web
    name: telegram-vote-bot
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python main.py"
    plan: free
    envVars:
      - key: TOKEN
        sync: false
      - key: ADMIN_ID
        sync: false
      - key: CHANNEL_ID
        sync: false
      - key: BOT_USERNAME
        sync: false
      - key: WELCOME_IMAGE_URL
        value: "https://your-image-hosting-service.com/welcome_image.png"
        sync: false

